package training.spring.blog

import jakarta.persistence.Entity
import jakarta.persistence.GeneratedValue
import jakarta.persistence.Id
import jakarta.persistence.ManyToOne
import java.time.LocalDateTime

// Not using Kotlin data classes as JPA is not designed to work
// with immutable classes or methods auto-generated by data classes
// Other Spring Data libraries (eg: Spring Data JDBC, Spring Data MongoDB) support data classes

@Entity
class Article(
    var title: String,
    var headline: String,
    var content: String,
    @ManyToOne var author: User,
    var slug: String = title.toSlug(),
    var addedAt: LocalDateTime = LocalDateTime.now(),
    @Id @GeneratedValue var id: Long? = null
)

// It is recommended to always use entities with generated IDs in Kotlin

@Entity
class User(
    var login: String,
    var firstname: String,
    var lastname: String,
    var description: String? = null,
    @Id @GeneratedValue var id: Long? = null
)
